### PR TITLE
FEAT: Add more gardients

### LINKED ISSUE #79: Adding more gradient
**Is your feature request related to a problem? Please describe.**

Currently we have 4 gradient, maybe adding more choices, 1 or two more.

Check https://hypercolor.dev/

**Describe the solution you'd like**

Copy name, tailwind classes and CSS native from hypercolor.dev

I don't have any preferences, but  I like the diversity. So please choose the theme that have very different vibes from the existing one.

### PR DESCRIPTION
**Pull request by FarhanRafid97**
Closes #79

## Description

add more gardient color for question background

[0165c1b4-299f-4876-85e9-98abf059a884.webm](https://github.com/mazipan/tanyaaja/assets/94950541/d709664b-e4a4-4ad0-bd2a-d7c739bb1bb7)

### CODE REVIEW

**Comment by mazipan** [comment]
Could you also check the UI on the small screen or mobile screen?
Just make sure it still well aligned.

**Comment by mazipan** [comment]
Also the custom OG still not support for white text.

So please choose the gradient that still looking good in Light Theme.

Check for both theme, dark and light.

Prioritize the one that have a good contrast ratio in the light and dark theme.

**Comment by FarhanRafid97** [comment]
how about this mas



[4989d4cc-c472-4367-bd18-149574b7f8e1.webm](https://github.com/mazipan/tanyaaja/assets/94950541/d6931452-01a8-4307-b837-a01f98dfe628)

**Review by mazipan — APPROVED** [review]
Looks good 👍

**Pull request merged**
