### PR TITLE
feat: add account visibility reminder component

### LINKED ISSUE #22: Add message box to remind user about showing their data in the eksplor page
**Is your feature request related to a problem? Please describe.**

Some users are not shown in the eksplor page, while it might intended, maybe we need to remind them about this feature.

**Describe the solution you'd like**

Add a message box in account page (https://www.tanyaaja.in/account) when the user still not allowing to be accessed in eksplor page

**Additional context**
The message box can be dismiss and should not be shown again for at least a week or a month

### PR DESCRIPTION
**Pull request by Namchee**
Closes #22 

## Description

This pull request adds reminder for account visibility settings in account settings page. It will be shown weekly whenever account visibility is not public.

## Current Tasks

- [x] Create `AccountVisibilityReminder` component
- [x] Create one week reminder logic
- [x] Hook the state with `public` value on the form

### CODE REVIEW

**Comment by mazipan** [comment]
Most visited page for a logged in user is /account, it is like a landing page for a logged in user.

/account/settings on the other hand, have a lower visit numbers.

By using this info, how about we prioritize to showing the reminder on the /account?

**Comment by mazipan** [comment]
Most visited page for a logged in user is /account, it is like a landing page for a logged in user.

/account/settings on the other hand, have a lower visit numbers.

By using this info, how about we prioritize to showing the reminder on the /account?

Also I am thinking about using https://ui.shadcn.com/docs/components/alert with a dismiss button, what do you think?

**Comment by Namchee** [comment]
Good idea, I'll show the callout on `/account` page then and utilize shadcn for that.

**Comment by Namchee** [comment]
After tidying this up, I think using `Toast` with infinite duration is better solution than using `Alert` because:

1. `Toast` is dismissable while `Alert` is not, which is better suited for reminders like this. While you can 'dismiss' alert by adding buttons to it, it is still faster to set `Toast` with infinite duration instead since it has built-in removal.
2. Account visibility is not a destructive state, therefore it should 'float' in non-obstructive way, which is a good use-case of `Toast`. `Alert` on the other hand is designed to be 'integrated' with the page flow.

This implementation will change if we can integrate the alert somewhere in the content. Do you have a UI design I can follow for this?

**Review by mazipan — APPROVED** [review]
Looks good for now

**Pull request merged**
