### PR TITLE
CHORE: Remove zod package

### LINKED ISSUE #78: Remove unused dependency: zod
Check the usable first, as we migrate the validation to Valibot, I guess we can remove zod for now

### PR DESCRIPTION
**Pull request by patHyatt**
Closes #78

## Description
Removes zod and replaces `.parse` use with a vanilla conversion function with validation

## Current Tasks
n/a

### CODE REVIEW

**Comment by mazipan** [comment]
We have Valibot installed, could we use that?

https://valibot.dev/

**Comment by patHyatt** [comment]
> We have Valibot installed, could we use that?
> 
> https://valibot.dev/

Probably. Checking, and will update PR if so

**Comment by patHyatt** [comment]
Updated with valibot schema use.

**Review by mazipan — DISMISSED** [review]
Looks solid

**Comment by mazipan** [comment]
The lockfile needs to be updated, please run `pnpm install` to update the pnpm-lock @patHyatt 

Screenshot 2023-10-16 at 16 11 09

**Comment by patHyatt** [comment]
@mazipan Apologies. Updated lock file, which removed the zod package

**Comment by mazipan** [comment]
Try running `pnpm run build` in your local.
The build is erro in Vercel

**Review by mazipan — APPROVED** [review]

**Comment by patHyatt** [comment]
🎉 

Sorry for the pains here @mazipan 

Thanks

**Pull request merged**
