### PR TITLE
fix: frontpage container view in 4k monitors #28

### LINKED ISSUE #28: Frontpage container didn't do so well with 4K monitors
**Describe the bug**
On the frontpage, there should be a container to contain the maximum width set by the CSS, so the person who open the website on a bigger monitor wouldn't be needing to move their heads left and right to see all the contents.

**To Reproduce**
1. Buy a 4K monitor
2. Open tanyaaja.in frontpage
3. Use normal scaling (4K 100%)

**Expected behavior**

It should not be spread wide, it should have some container that set a certain maximum width

**Screenshots**

1080p (basically a 4K monitor, scaled to 200%)
image

4K
image

**Additional context**
None

### PR DESCRIPTION
**Pull request by antheiz**
Closes https://github.com/mazipan/tanyaaja/issues/28

### CODE REVIEW

**Review by aldy505 — APPROVED** [review]
LGTM. But while you're here, can you also not just add the `container` class on the viewport, but also handle for this flexbox/grid inconsistencies?

image

It'd also be okay if it's done on a separate PR.

**Comment by antheiz** [comment]
Thanks for the feedback. I'll do it.

**Review by mazipan — APPROVED** [review]
LGTM 🚀

**Comment by mazipan** [comment]
Thank you @antheiz & @aldy505 🙌

**Pull request merged**
